/// Extension trait for ABI representation.
///
/// Implemented by types generated by the [`sol!`] macro when using the [`#[sol(abi)]`][attr]
/// attribute.
///
/// [`sol!`]: crate::sol
/// [attr]: https://docs.rs/linera-alloy-sol-macro/latest/linera_alloy_sol_macro/macro.sol.html#attributes
pub trait JsonAbiExt {
    /// The ABI representation of this type.
    type Abi;

    /// Returns the ABI representation of this type.
    fn abi() -> Self::Abi;
}
